name: DeadByDaylight
version: 1.0.0
api-version: "1.15"
main: net.ignissak.deadbydaylight.DeadByDaylight
authors: [iGniSsak]
load: "POSTWORLD"
depend: ["CraftCore", "CraftLibs", "CraftEconomy", "WorldGuard", "XoreBoardUtil", "HolographicDisplays", "Citizens", "LibsDisguises"]
commands:
  forcestart: {}
  role: {}
  stats: {}
  setlobby: {}
  addkillerspawn: {}
  addsurvivorspawn: {}
  adddrop: {}
  addgenerator: {}
  addlootchest: {}
  addfireworkspawn: {}
  setneededgenerators: {}